name: InfernalMobs
main: com.jacob_vejvoda.infernal_mobs.InfernalMobs
version: 5.1
depend: [NyaaCore]
softdepend: [Vault]
api-version: 1.13
commands:
  infernalmobs:
    aliases: [im]
    description: This is the infernal mobs base commands.
    usage: /<command>
    permission: infernal_mobs.commands
    permission-message: You don't have <permission>
